version: "3"
services:

### API #################################################
  api:
    container_name: vue_ssr_sample_api
    build:
      context: .
      dockerfile: ./docker/api
    volumes:
      - /usr/src/api
    ports:
      - "8082:8082"
    environment:
      - NODE_ENV=prod
      - MONGO_URI=mongo
      - MONGO_PORT=27017
      - MONGO_DB=vue_ssr_sample
      - PORT=8082
    networks:
      - db_ohako_bridge

### WEB ##################################################
  app:
    container_name: vue_ssr_sample_app
    build:
      context: .
      dockerfile: ./docker/app
    environment:
      - NODE_ENV=prod
      - PORT=8081
    volumes:
      - /usr/share/nginx/html
    ports:
      - "80:80"

networks:
  db_vue_ssr_sample_bridge:
    external: true
